# @author dharmaraj.pawale@sterlite.com
# @copyright Sterlite Technologies Ltd.
# @creationdate 20-Aug-2020


#server:
#  port: 8085
#  servlet:
#    context-path: /oauth2_client
#    session:
#      cookie:
#        name: CLIENT_SESSION

#security:
#  oauth2:
#    client:
#      clientId: client-id
#      clientSecret: client-secret
#      accessTokenUri: http://localhost:8082/auth/oauth/token
#      userAuthorizationUri: http://localhost:8082/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8082/auth/rest/hello/principal

#spring:
#  thymeleaf:
#    cache: false